version: '3'
services:
  ssn_validator_api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql_forexapi_db
    restart: always
    networks:
      - mt-network
    
  
  mysql_forexapi_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: forexapi
      MYSQL_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./storage/dbdata:/var/lib/mysql
 
    ports:
      - "3308:3308"
    networks:
      - mt-network

networks:
  mt-network:
    driver: bridge